import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, resolve, sep } from 'node:path';
import { env } from '../config/env';

/**
 * File storage for uploads. Local disk for now, behind this small interface
 * so moving to object storage later only changes this file.
 */
export interface Storage {
  put(key: string, data: Buffer): Promise<void>;
  read(key: string): Promise<Buffer | null>;
  remove(key: string): Promise<void>;
}

function localDisk(rootDir: string): Storage {
  const root = resolve(rootDir);
  // Keys are generated by us, but refuse anything that would escape the root anyway.
  const pathFor = (key: string) => {
    const full = resolve(root, key);
    if (!full.startsWith(root + sep)) throw new Error(`Invalid storage key: ${key}`);
    return full;
  };

  return {
    async put(key, data) {
      const path = pathFor(key);
      await mkdir(dirname(path), { recursive: true });
      await writeFile(path, data);
    },
    async read(key) {
      try {
        return await readFile(pathFor(key));
      } catch (err) {
        if ((err as NodeJS.ErrnoException).code === 'ENOENT') return null;
        throw err;
      }
    },
    async remove(key) {
      await rm(pathFor(key), { force: true });
    },
  };
}

export const storage: Storage = localDisk(env.UPLOAD_DIR);
